/**
 * Motivational quotes for study – shown randomly on quiz completion.
 */
export const STUDY_QUOTES = [
  "The expert in anything was once a beginner.",
  "Learning is a treasure that will follow its owner everywhere.",
  "Study hard, for the well is deep and our brains are shallow.",
  "The beautiful thing about learning is that no one can take it away from you.",
  "Education is the passport to the future, for tomorrow belongs to those who prepare for it today.",
  "The more that you read, the more things you will know. The more that you learn, the more places you'll go.",
  "Learning never exhausts the mind.",
  "Develop a passion for learning. If you do, you will never cease to grow.",
  "Study the past if you would define the future.",
  "An investment in knowledge pays the best interest.",
  "The capacity to learn is a gift; the ability to learn is a skill; the willingness to learn is a choice.",
  "Learning is not attained by chance, it must be sought for with ardor and diligence.",
  "The roots of education are bitter, but the fruit is sweet.",
  "Education is what remains after one has forgotten what one has learned in school.",
  "Live as if you were to die tomorrow. Learn as if you were to live forever.",
  "The only person who is educated is the one who has learned how to learn and change.",
  "Learning is not a spectator sport.",
  "Success is the sum of small efforts, repeated day in and day out.",
  "Don't let what you cannot do interfere with what you can do.",
  "Believe you can and you're halfway there.",
  "It does not matter how slowly you go as long as you do not stop.",
  "The secret of getting ahead is getting started.",
  "You don't have to be great to start, but you have to start to be great.",
  "Small progress is still progress.",
  "Every expert was once a beginner. Every master was once a student.",
  "The best time to plant a tree was 20 years ago. The second best time is now.",
  "Your limitation—it's only your imagination.",
  "Great things never come from comfort zones.",
  "Dream it. Wish it. Do it.",
  "Success doesn't come to you, you go to it.",
  "The harder you work for something, the greater you'll feel when you achieve it.",
  "Dream bigger. Do bigger.",
  "Don't stop when you're tired. Stop when you're done.",
  "Wake up with determination. Go to bed with satisfaction.",
  "Do something today that your future self will thank you for.",
  "Little things make big days.",
  "It's going to be hard, but hard does not mean impossible.",
  "Believe in yourself. You are braver than you think, more talented than you know.",
  "Success is not final, failure is not fatal: it is the courage to continue that counts.",
  "The only way to do great work is to love what you do.",
  "You are never too old to set another goal or to dream a new dream.",
  "Learning is a gift. Even when pain is your teacher.",
  "Today a reader, tomorrow a leader.",
  "The best way to predict your future is to create it.",
  "Knowledge is power. Information is liberating.",
  "A person who never made a mistake never tried anything new.",
  "The mind is not a vessel to be filled but a fire to be kindled.",
  "Study without desire spoils the memory, and it retains nothing that it takes in.",
  "Learning is like rowing upstream: not to advance is to drop back.",
  "The expert in anything was once a beginner.",
  "Education is the key to unlock the golden door of freedom.",
  "Learn from yesterday, live for today, hope for tomorrow.",
  "The more I learn, the more I realize how much I don't know.",
  "Start where you are. Use what you have. Do what you can.",
];

/** Returns one random quote from the list. */
export function getRandomQuote() {
  return STUDY_QUOTES[Math.floor(Math.random() * STUDY_QUOTES.length)];
}
